### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JoahDave** [1lann/Mimic#65]
Im pretty new to CC so I'm not sure if this is a CC crash or a crash caused by the emulator.

Half of the time I try to use the pastebin command it freezes then crashes with: "Fatal | Thread unresponsive" 

That might be the emulator but that also may be what I'm getting. (Ink by Oeed)

Hopefully you can take a look at this!
Love the emulator!

**Comment by 1lann** [comment]
I can't seem to reproduce it, could you provide some logs from the JavaScript console?

**Comment by JoahDave** [comment]
The what what what?

**Comment by JoahDave** [comment]
This crash also occurs when running programs. (Example: Ink by Oeed)
Either this crash or "String ink: Too long without yielding"

**Comment by apemanzilla** [comment]
This sounds like a problem with your browser being slow. What browser are you using and what are your specs?

**Comment by JoahDave** [comment]
Firefox 64 bit Unlimited storage (Ram and SSD) Pretty slow internet :(

**Comment by apemanzilla** [comment]
Unlimited storage? Wat?

What is your processor and memory, those are the two key factors here. For example, I use an AMD FX-6300 processor overclocked to 4.5 GHz, and have 16 GB of DDR3-1600 memory.

**Comment by 1lann** [comment]
Perhaps try using sunspider to test your performance? https://www.webkit.org/perf/sunspider-1.0.2/sunspider-1.0.2/driver.html

Also to show the JavaScript console, right click on blank area on page -> Inspect element -> Debugger/Console tab

Could you also post EXACT steps to reproduce the problem?

**Comment by JoahDave** [comment]
Apparently this crash only occurs in Safari. I could not reproduce it in any other browser. Do you need me to run the test and give you the exact steps now that I know what the problem is?

**Comment by JoahDave** [comment]
You might want to add something like: "May not work correctly in Safari"

Again, is this closed or are you planning to make a fix just for Safari?

**Comment by 1lann** [comment]
Sorry I forgot to reply, I'll take a look at it sometime, however with my
experiences so far there doesn't see to be any problems when I use safari.

**Comment by JoahDave** [comment]
Safari seems to just give up when something is hard. Or at least that's what happens when I try to use the pastebin command. It just freezes and crashes.

**Comment by 1lann** [comment]
I can't seem to reproduce it, however yielding is done per Lua function call basis, and thread unresponsiveness errors occur when you haven't yielded for 5 seconds. I tried doing some profiling, Safari yielded no results as it captured nothing for some reason, and Chrome stated that the longest call to JavaScript (single yield) lasted for 300 ms, and that was when I was opening Ink. That isn't enough to cause a too long without yielding or a thread unresponsive error. You'll need that to be slower by a factor of 10 before it has the chance of having too long without yielding.

I really cannot see any performance issues and I cannot reproduce the problem, it works perfectly fine for me on Safari 8.0.2 on Yosemite 10.10.1. Are you not running any ComputerCraft "OSes" or additional programs that are running in the background of ComputerCraft that could cause slow downs? How do other emulators run on your computer?

**Comment by JoahDave** [comment]
I am running jupiterOS in the background and I haven't tried any other emulators.

**Comment by 1lann** [comment]
Could you try not running jupiterOS?

**Comment by JoahDave** [comment]
Yes I tried this. Same result.

**Comment by 1lann** [comment]
Try doing a `for i = 1, 10000000 do print(i) end` and tell me what number you end at.

**Comment by JoahDave** [comment]
251

**Comment by 1lann** [comment]
Although your computer seems abnormally slow (that's around the same number I get on my phone, on my computer I can get up to 1000), I really cannot reproduce this problem. Even my phone with Chrome can pastebin get ink and run ink with no issues. It might really just be that your computer is too slow which is really strange because Macs shouldn't be that slow to the extent of my phone. Unless someone can provide a lead to what would be causing the problem, I cannot resolve this. I'd say just avoid using Safari for Mimic.

**Comment by JoahDave** [comment]
I'm using a PC btw...
Yes I agree with that. Safari is just bad. I recently made a browser I call BOS from scratch and it can handle pastebin and stuffs just fine. 

I was going to close this issue but I decided to wait and let you give the last call.

**Comment by 1lann** [comment]
Alright then, closed until someone can provide a lead for this problem.

**Comment by 1lann** [comment]
Waititiawiwait you're using Safari on a PC????!?! Apple has dropped support for Safari on PC 2 years ago... Are you really using that old of a version of Safari on a Windows computer?

**Comment by JoahDave** [comment]
Nah, I was pulling you leg!
I've gotten away with saying that to far too many people who don't even notice.
Looks like your smarter than that!

**Comment by apemanzilla** [comment]
While we're on this topic, every time I try to use pastebin on Chrome, it always fails with a 503 in the javascript console. Same result in Firefox and (blah) Internet Explorer.

**Comment by 1lann** [comment]
@apemanzilla I'm using a CORS proxy hosted by Yahoo, so there's really nothing I can do about the 503s from Yahoo's servers. I could switch it to one that I own in the future, or perhaps a better CORS proxy.

@JoahDave wait so are you using a Mac or a Windows computer? And were you really using Safari/did this problem actually exist?

**Comment by apemanzilla** [comment]
Maybe allow the user to specify a custom proxy IP/URL?

I should probably split this into it's own issue.

**Comment by JoahDave** [comment]
@1lann I'm using Mac and yes this existed. I only tried to pull your leg on the last post. It was meant as a joke, let's keep it that way!
