### ISSUE TITLE
HTTP API isn't working correctly

### ISSUE THREAD

**Issue by JerryWester** [1lann/Mimic#77]
Whenever I try to use pastebin or a custom program which uses HTTP functions, the computer just hangs. It doesn't freeze, but it doesn't connect to pastebin either. And there's no "Too long without yielding" error. I can terminate the program, or open up a program in the sidebar to edit. I'm using ChromeOS as my operating system (and, obviously, Chrome as the browser). I'll soon get a javascript log.

**Comment by 1lann** [comment]
Sorry but Mimic isn't maintained anymore, so don't expect it to be fixed anytime soon (which is why I also changed the license to MIT). You can feel free to fork it and fix it yourself though.

**Comment by JerryWester** [comment]
It isn't? Well, then... I'm not an expert with GitHub, but I'll give your suggestion a go. Thanks
